


services:

  authsvc:
    image: oc/auth-svc
    build: ./auth-svc

    env_file:
      - odontocare.env

    networks:
      - oc-backend

  adminsvc:
    image: oc/admin-svc
    build: ./admin-svc

    networks:
      - oc-backend
    env_file:
      - odontocare.env


  agendasvc:
    image: oc/agenda-svc
    build: ./agenda-svc

    env_file:
      - odontocare.env

    networks:
      - oc-backend


  apisvc:
    image: oc/api-gateway
    build: ./api-gateway
    depends_on:
      - authsvc
      - adminsvc
      - agendasvc
    env_file:
      - odontocare.env
    ports:
      - "4000:4000"
  
    networks:
      - oc-backend
      - oc-frontend


networks:
  oc-backend:
  
  oc-frontend:

